// EN: MaterialCatalog.hpp briefly defines this Dinotofu module and its responsibilities.
// FR: MaterialCatalog.hpp résume brièvement ce module de Dinotofu et ses responsabilités.
// English: This file is part of Dinotofu. Code identifiers are written in English, while player-facing text can stay in French.
// Français : Ce fichier fait partie de Dinotofu. Les identifiants du code sont en anglais, tandis que les textes affichés au joueur peuvent rester en français.
// English: Creates early stackable materials, plants, books and information entries.
// Français : Crée les premiers matériaux, plantes, livres et renseignements empilables.

#ifndef INCLUDE_ITEM_MATERIAL_MATERIALCATALOG_HPP
#define INCLUDE_ITEM_MATERIAL_MATERIALCATALOG_HPP

#include "item/material/Material.hpp"

#include <string>

class MaterialCatalog
{
public:
    static Material createById(const std::string& id, int quantity = 1, const std::string& quality = "normal");
    static Material createGoblinEar(int quantity = 1);
    static Material createWolfFang(int quantity = 1);
    static Material createRustedMetalFragment(int quantity = 1);
    static Material createRunicIronShard(int quantity = 1);
    static Material createPolishedScalePlate(int quantity = 1);
    static Material createAmberTemperingOil(int quantity = 1);
    static Material createWornLeatherPiece(int quantity = 1);
    static Material createMountainBlueFlower(int quantity = 1);
    static Material createBitterHealingLeaf(int quantity = 1);
    static Material createCommonGoblinNotes(int quantity = 1);
    static Material createCommonWolfNotes(int quantity = 1);
    static Material createBasicPlantManual(int quantity = 1);
    static Material createBasicMagicManual(int quantity = 1);
    static Material createArcaneBindingGrimoire(int quantity = 1);
    static Material createElementalWardGrimoire(int quantity = 1);
    static Material createResistanceRiftGrimoire(int quantity = 1);
    static Material createFrostNeedleGrimoire(int quantity = 1);
    static Material createManaSutureGrimoire(int quantity = 1);
    static Material createOccultBrambleGrimoire(int quantity = 1);
    static Material createCrackedBone(int quantity = 1);
    static Material createArcaneDust(int quantity = 1);
    static Material createMinorFireRuneNote(int quantity = 1);
    static Material createMinorColdRuneNote(int quantity = 1);
    static Material createSlimeResidue(int quantity = 1);
    static Material createVariationResidue(int quantity = 1);
    static Material createBattleTornBadge(int quantity = 1);
    static Material createWeakRepairKit(int quantity = 1);
    static Material createMediumRepairKit(int quantity = 1);
    static Material createBigRepairKit(int quantity = 1);
    static Material createTinkererCompleteRepairKit(int quantity = 1);
    static Material createSmallRepairKit(int quantity = 1);
    static Material createReinforcedRepairKit(int quantity = 1);
    static Material createSpecialAdventurerNotes(int quantity = 1);
    static Material createSummoningNotes(int quantity = 1);
    static Material createBossIdentityScrap(int quantity = 1);
    static Material createPotionRecipePage(int quantity = 1);
    static Material createRepairRecipePage(int quantity = 1);
    static Material createAdvancedMonsterNotes(int quantity = 1);
    static Material createClientRecommendation(int quantity = 1);
    static Material createGuildFavorToken(int quantity = 1);
    static Material createLocalServiceLetter(int quantity = 1);
    static Material createGuildCard(int quantity = 1);
    static Material createGuildRankFNotice(int quantity = 1);
    static Material createGuildReliabilityGreenPellet(int quantity = 1);
    static Material createTravelPassNote(int quantity = 1);
    static Material createWarmMealVoucher(int quantity = 1);
    static Material createCityServiceStamp(int quantity = 1);
    static Material createMunicipalProofLetter(int quantity = 1);
    static Material createLodgingBedToken(int quantity = 1);
    static Material createStableStallTicket(int quantity = 1);
    static Material createCaravanSeatTicket(int quantity = 1);
    static Material createGuardedTransportPass(int quantity = 1);
    static Material createRouteTollReceipt(int quantity = 1);
    static Material createLocalReputationNote(int quantity = 1);
    static Material createLocalServiceWarning(int quantity = 1);
    static Material createFireLantern(int quantity = 1);
    static Material createNightSurvivalKit(int quantity = 1);
    static Material createSurvivalRation(int quantity = 1);
    static Material createThermalSurvivalBlanket(int quantity = 1);
    static Material createCoolingSurvivalWrap(int quantity = 1);
    static Material createTemperatureSurvivalKit(int quantity = 1);
    static Material createTravelDistanceMark(int quantity = 1);
    static Material createPreparedSaddlebags(int quantity = 1);
    static Material createTemporaryStableStorage(int quantity = 1);
    static Material createRouteScoutNote(int quantity = 1);
    static Material createRentalMountVoucher(int quantity = 1);
    static Material createStableBoxReservation(int quantity = 1);
    static Material createLoadedPackSaddle(int quantity = 1);
    static Material createRelayRouteBadge(int quantity = 1);
    static Material createOwnedMountRegistration(int quantity = 1);
    static Material createMountFatigueMarker(int quantity = 1);
    static Material createMountRestCare(int quantity = 1);
    static Material createStableSaddleUpgrade(int quantity = 1);
    static Material createMountNameTag(int quantity = 1);
    static Material createMountTemperamentCalm(int quantity = 1);
    static Material createMountBondMarker(int quantity = 1);
    static Material createMountMinorInjuryMarker(int quantity = 1);
    static Material createMountComfortBridle(int quantity = 1);
    static Material createMountGroomingKit(int quantity = 1);
    static Material createMountWeatherBlanket(int quantity = 1);
    static Material createMountPackHarness(int quantity = 1);
    static Material createMountRouteMemoryMarker(int quantity = 1);
    static Material createMountSurefootTrainingMarker(int quantity = 1);
    static Material createMountRoadShoes(int quantity = 1);
    static Material createRunicExtractionNote(int quantity = 1);
    static Material createRunicSafetySeal(int quantity = 1);
    static Material createRunicTransferNote(int quantity = 1);
    static Material createRunicOverloadLimitNote(int quantity = 1);
    static Material createRunicStabilizer(int quantity = 1);
    static Material createRareFireRuneCore(int quantity = 1);
    static Material createRareColdRuneCore(int quantity = 1);
    static Material createNecromancyWarning(int quantity = 1);
    static Material createMagicLearningNotes(int quantity = 1);
    static Material createElementalWeaknessNotes(int quantity = 1);
    static Material createBeastHide(int quantity = 1);
    static Material createShadowThread(int quantity = 1);
    static Material createKitsuneEmber(int quantity = 1);
    static Material createDraconicScaleFragment(int quantity = 1);
    static Material createUnstableCore(int quantity = 1);
    static Material createFitoriaFeather(int quantity = 1);
    static Material createZelefDemonBlood(int quantity = 1);
    static Material createAtlasBrokenPlate(int quantity = 1);
    static Material createLyknirHuntShard(int quantity = 1);
    static Material createGrinkaAvariceCoin(int quantity = 1);
    static Material createAzelanosDarkCrownShard(int quantity = 1);
    static Material createThamarysOriginScale(int quantity = 1);
    static Material createMojoAncientSeed(int quantity = 1);
    static Material createInakariMirrorShard(int quantity = 1);
    static Material createSilentJudgmentSeal(int quantity = 1);
    static Material createAnomalyGlitchFragment(int quantity = 1);
    static Material createDeadMinuteGear(int quantity = 1);
    static Material createBuriedBoneLullaby(int quantity = 1);
    static Material createBorosWarMark(int quantity = 1);
    static Material createAnastasiaBoundHeart(int quantity = 1);
    static Material createLexiorJusticeSplinter(int quantity = 1);
    static Material createLunarDreamFragment(int quantity = 1);
    static Material createElementalFusionCore(int quantity = 1);
    static Material createHumanWillFragment(int quantity = 1);
    static Material createConsciousLuckShard(int quantity = 1);
    static Material createProgressionSeal(int quantity = 1);
    static Material createAbsentThroneFragment(int quantity = 1);
    static Material createLostNameFragment(int quantity = 1);
    static Material createAldebarothAbyssResidue(int quantity = 1);
    static Material createTwinParadoxShard(int quantity = 1);
    static Material createOberionOriginThread(int quantity = 1);
    static Material createFacelessBreath(int quantity = 1);
    static Material createPuppetNail(int quantity = 1);
    static Material createMoiranFateThread(int quantity = 1);
    static Material createLostSoulAntler(int quantity = 1);
    static Material createGorvaldRoyalBlood(int quantity = 1);
    static Material createSeranaRoyalFang(int quantity = 1);
    static Material createDraiiteBlackSilk(int quantity = 1);
    static Material createBrokenMirrorShard(int quantity = 1);
    static Material createUnstableVersionCore(int quantity = 1);
    static Material createPrecisionHarvestTools(int quantity = 1);
    static Material createPreservationVials(int quantity = 1);
    static Material createCleanHarvestManual(int quantity = 1);
    static Material createMonsterDissectionGuide(int quantity = 1);
    static Material createTrainingArrows(int quantity = 1);
    static Material createTrainingBolts(int quantity = 1);
    static Material createTrainingThrowingKnives(int quantity = 1);
    static Material createBarbedArrows(int quantity = 1);
    static Material createPiercingBolts(int quantity = 1);
    static Material createBalancedThrowingKnives(int quantity = 1);
    static Material createAshArrows(int quantity = 1);
    static Material createFrozenBolts(int quantity = 1);
    static Material createConductiveKnives(int quantity = 1);
    static Material createVenomArrows(int quantity = 1);
    static Material createShockBolts(int quantity = 1);
    static Material createSmokeKnives(int quantity = 1);
    static Material createMyceliumLantern(int quantity = 1);
    static Material createEchoingResin(int quantity = 1);
    static Material createSunDriedClay(int quantity = 1);
    static Material createMoonlitSalt(int quantity = 1);
    static Material createOldCoinBundle(int quantity = 1);
    static Material createGlassMapFragment(int quantity = 1);
    static Material createLivingVineFiber(int quantity = 1);
    static Material createColdIronNail(int quantity = 1);
    static Material createWitchBottle(int quantity = 1);
    static Material createForgottenCampTag(int quantity = 1);
    static Material createTinyGearSpring(int quantity = 1);
    static Material createInkedContractScrap(int quantity = 1);

    static Material createFireflyIronShell(int quantity = 1);
    static Material createWhisperingArchivePage(int quantity = 1);
    static Material createGreyDrakeScale(int quantity = 1);
    static Material createCarnivalTicketShred(int quantity = 1);
    static Material createMirrorGlassBead(int quantity = 1);
    static Material createTidewornInk(int quantity = 1);
    static Material createCliffBasilLeaf(int quantity = 1);
    static Material createRustedGearCore(int quantity = 1);
    static Material createSaltedRopeKnot(int quantity = 1);
    static Material createLuminousMothWing(int quantity = 1);

    static Material createHolyWaterVial(int quantity = 1);
    static Material createSanctuaryCandle(int quantity = 1);
    static Material createExorcismIncense(int quantity = 1);
    static Material createBlessingNote(int quantity = 1);
    static Material createExorcistNote(int quantity = 1);
    static Material createCrackedBellClapper(int quantity = 1);
    static Material createSanctuaryWaxSeal(int quantity = 1);
    static Material createChurchNightTestimony(int quantity = 1);
    static Material createChurchSleepDiagnosis(int quantity = 1);
    static Material createNamedOathTestimony(int quantity = 1);
    static Material createSharedDreamPattern(int quantity = 1);
    static Material createCopiedCounterLegend(int quantity = 1);
    static Material createIdentifiedSourceObject(int quantity = 1);
    static Material createSealableSourceSketch(int quantity = 1);
    static Material createPactBreakWitness(int quantity = 1);
    static Material createSourceDefeatNotice(int quantity = 1);
    static Material createPurifiedSourceAshes(int quantity = 1);
    static Material createBrokenOathRecord(int quantity = 1);
    static Material createClosedCounterLegend(int quantity = 1);
    static Material createSealedSourceMark(int quantity = 1);
    static Material createReleasedPactRecord(int quantity = 1);
    static Material createConfirmedSourceSilence(int quantity = 1);
    static Material createBlueMistReed(int quantity = 1);
    static Material createMistglassPearl(int quantity = 1);
    static Material createWhiteBoneChalk(int quantity = 1);
    static Material createBuriedGiantChip(int quantity = 1);
    static Material createSmugglerToken(int quantity = 1);
    static Material createSealedDebtSlip(int quantity = 1);
    static Material createBlackMarketBarterSeal(int quantity = 1);

    static Material createCityRepairDaysMarker(int quantity = 1);
    static Material createCityDamageNotice(int quantity = 1);
    static Material createCityDefenseMedal(int quantity = 1);
    static Material createCityDefenseGratitudeMarker(int quantity = 1);
    static Material createCityEventRecentMarker(int quantity = 1);
    static Material createCityRepairReceipt(int quantity = 1);
    static Material createWeepingStoneTear(int quantity = 1);
    static Material createPetrifiedRosePetals(int quantity = 1);
};

#endif
