#!/usr/bin/env bash
set -euo pipefail

TEST_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${TEST_ROOT_DIR}"

fail() { echo "[FAIL] $1" >&2; exit 1; }
pass() { echo "[OK] $1"; }

VERSION="$(bash ./scripts/get_version.sh)"
[[ -n "$VERSION" ]] || fail "version introuvable"
[[ "$(cd /tmp && bash "${TEST_ROOT_DIR}/scripts/get_version.sh")" == "$VERSION" ]] || fail "get_version.sh dépend du dossier courant"
[[ -x ./output/Dinotofu ]] || fail "output/Dinotofu absent : make test doit dépendre du build"
[[ "$(./output/Dinotofu --version)" == *"V${VERSION}"* ]] || fail "version binaire incohérente"
pass "version ${VERSION} cohérente"

[[ -f CHANGELOG.md ]] || fail "CHANGELOG.md manquant"
[[ -f CHANGELOG_FR.md ]] || fail "CHANGELOG_FR.md manquant"
grep -q "V${VERSION}" CHANGELOG.md || fail "CHANGELOG sans V${VERSION}"
grep -q "V${VERSION}" CHANGELOG_FR.md || fail "CHANGELOG_FR sans V${VERSION}"
[[ ! -f PATCHNOTE_DINOTOFU.md && ! -f PATCHNOTE_DINOTOFU_FR.md ]] || fail "anciens PATCHNOTE encore présents"
pass "CHANGELOG anglais/français remplacent les PATCHNOTE"

! grep -q "V3.30.00" README.md || fail "historique de versions revenu dans README.md"
! grep -q "V3.30.00" READMEFR.md || fail "historique de versions revenu dans READMEFR.md"
pass "README sans historique détaillé"

if find scripts -type f -name '*.sh' -exec grep -Il $'\r' {} + | grep -q .; then
    fail "scripts shell avec fins de ligne CRLF incompatibles Linux"
fi
pass "scripts shell portables en fins de ligne LF"

if find src include -type f -name '*.inc' | grep -q .; then
    fail "des fichiers .inc existent encore dans src/include"
fi
pass "aucun .inc dans src/include"

[[ -f src/core/GameSetup.cpp ]] || fail "création/configuration de partie non extraite de Game.cpp"
[[ -f src/core/GameStory.cpp ]] || fail "runtime histoire non extrait de Game.cpp"
[[ -f src/interface/menu/quest/QuestLocationNpcMenu.cpp && -f src/interface/menu/quest/QuestClientNavigationSupport.cpp ]] || fail "navigation lieux/PNJ de quête non modularisée"
[[ -f src/interface/menu/quest/QuestStoryMenu.cpp && -f src/interface/menu/quest/QuestStorySupport.cpp && -f include/interface/menu/quest/QuestStorySupport.hpp ]] || fail "gestion histoire de QuestMenu non modularisée"
[[ -f src/interface/menu/quest/QuestExplorationMenu.cpp && -f include/interface/menu/quest/QuestExplorationSupport.hpp && -f include/interface/menu/quest/QuestMenuInternalSupport.hpp ]] || fail "moteur d'exploration de QuestMenu non modularisé"
[[ -f src/interface/menu/quest/QuestPresentationSupport.cpp && -f include/interface/menu/quest/QuestPresentationSupport.hpp ]] || fail "présentation partagée des quêtes non modularisée"
[[ -f src/combat/turn/wave/PlayerWaveTacticalActionMenu.cpp && -f include/combat/turn/wave/PlayerWaveTacticalActionMenu.hpp ]] || fail "menu tactique de vague non extrait"
[[ -f src/combat/turn/wave/PlayerWaveTacticalSupport.cpp && -f include/combat/turn/wave/PlayerWaveTacticalSupport.hpp ]] || fail "helpers tactiques de vague non modularisés"
[[ $(wc -l < src/core/Game.cpp) -lt 4000 ]] || fail "Game.cpp a regrossi au-delà de 4000 lignes"
[[ $(wc -l < src/interface/menu/quest/QuestMenu.cpp) -lt 7000 ]] || fail "QuestMenu.cpp a regrossi au-delà de 7000 lignes"
[[ $(wc -l < src/combat/turn/wave/PlayerWaveCombatTurn.cpp) -lt 700 ]] || fail "PlayerWaveCombatTurn.cpp a regrossi au-delà de 700 lignes"
[[ $(wc -l < src/combat/turn/wave/PlayerWaveTacticalActionMenu.cpp) -lt 3200 ]] || fail "PlayerWaveTacticalActionMenu.cpp a regrossi au-delà de 3200 lignes"
pass "modularisation Game/QuestMenu/PlayerWaveCombatTurn et tactiques protégée contre les régressions"

[[ -f include/entity/player/PlayerHistoryTypes.hpp && -f src/entity/player/PlayerHistory.cpp ]] || fail "module mémoire/rivaux absent"
grep -q 'struct PlayerRivalRecord' include/entity/player/PlayerHistoryTypes.hpp || fail "PlayerRivalRecord absent"
grep -q 'recordRivalReturn' src/entity/player/PlayerHistory.cpp || fail "retours de rivaux absents"
[[ -f include/combat/rival/RivalEmergenceSystem.hpp && -f src/combat/rival/RivalEmergenceSystem.cpp ]] || fail "sélection des rivaux absente"
grep -q 'Aucun rival créé' src/combat/turn/wave/MonsterWaveCombatTurn.cpp || fail "fuite ordinaire non distinguée d'un rival"
RIVAL_TEST_BIN="$(mktemp /tmp/dinotofu_rival_test.XXXXXX)"
trap 'rm -f "$RIVAL_TEST_BIN"' EXIT
g++ -std=c++17 -Wall -Wextra -Iinclude tests/RivalEmergenceSystemTest.cpp src/combat/rival/RivalEmergenceSystem.cpp -o "$RIVAL_TEST_BIN"
"$RIVAL_TEST_BIN" >/dev/null || fail "logique de sélection des rivaux invalide"
rm -f "$RIVAL_TEST_BIN"
trap - EXIT
pass "mémoire persistante, fuites ordinaires et rivaux testés"

[[ -f include/progression/language/LanguageSystem.hpp && -f src/progression/language/LanguageSystem.cpp ]] || fail "système de langues absent"
[[ -f include/combat/dialogue/EncounterDialogueSystem.hpp && -f src/combat/dialogue/EncounterDialogueSystem.cpp ]] || fail "dialogues de rencontre multilingues absents"
grep -q 'languageKnowledge' src/save/SaveManager.cpp || fail "sauvegarde des langues absente"
SAVE_SCHEMA_VERSION="$(sed -n 's/.*inline constexpr int Current = \([0-9][0-9]*\);.*/\1/p' include/save/SaveSchemaVersion.hpp | head -n 1)"
[[ -n "$SAVE_SCHEMA_VERSION" ]] || fail "schéma de sauvegarde courant introuvable"
grep -q 'SaveSchemaVersion::Current' src/save/SaveManager.cpp || fail "SaveManager n'utilise pas le schéma de sauvegarde centralisé"
grep -q 'language_goblin_primer' src/economy/shop/LibraryInformationCatalog.cpp || fail "cours de bibliothèque absents"
grep -q 'QuestLanguageSystem::canRead' src/interface/menu/quest/QuestMenu.cpp || fail "contrats étrangers non reliés au journal"
LANG_TEST_BIN="$(mktemp /tmp/dinotofu_language_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -ffunction-sections -fdata-sections -Iinclude tests/LanguageSystemTest.cpp src/progression/language/LanguageSystem.cpp -Wl,--gc-sections -o "$LANG_TEST_BIN"
"$LANG_TEST_BIN" >/dev/null || fail "catalogue de langues invalide"
rm -f "$LANG_TEST_BIN"
QUEST_LANG_TEST_BIN="$(mktemp /tmp/dinotofu_quest_language_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -ffunction-sections -fdata-sections -Iinclude tests/QuestLanguageSystemTest.cpp src/quest/language/QuestLanguageSystem.cpp -Wl,--gc-sections -o "$QUEST_LANG_TEST_BIN"
"$QUEST_LANG_TEST_BIN" >/dev/null || fail "affectation des langues de quête invalide"
rm -f "$QUEST_LANG_TEST_BIN"
pass "langues, bibliothèque, dialogues et contrats étrangers testés"

[[ -f include/adventure/flavor/ExplorationLanguageTrace.hpp && -f src/adventure/flavor/ExplorationLanguageTrace.cpp ]] || fail "traces linguistiques d'exploration absentes"
[[ -f include/adventure/content/BiomeLivingContentCatalog.hpp && -f src/adventure/content/BiomeLivingContentCatalog.cpp ]] || fail "contenu vivant structuré des biomes absent"
[[ -f include/world/npc/LivingNpcProfile.hpp && -f src/world/npc/LivingNpcProfile.cpp ]] || fail "profil PNJ vivant absent"
[[ -f include/world/npc/NpcKnownFact.hpp && -f src/entity/player/PlayerNpcMemory.cpp ]] || fail "mémoire factuelle persistante des PNJ absente"
grep -q 'BiomeLivingContentCatalog::buildCurrentObservationLines' src/interface/menu/quest/QuestExplorationMenu.cpp || fail "contenu vivant des biomes non relié à l'exploration"
grep -q 'BiomeAmbientEventSystem::buildCurrentEvent' src/interface/menu/quest/QuestExplorationMenu.cpp || fail "micro-événements de biome non reliés à l'exploration"
grep -q 'ExplorationLanguageTraceCatalog::renderForPlayer' src/interface/menu/quest/QuestExplorationMenu.cpp || fail "traces linguistiques non reliées à l'exploration"
LIVING_WORLD_TEST_BIN="$(mktemp /tmp/dinotofu_living_world_test.XXXXXX)"
PROJECT_OBJECTS_LIVING="$(find build -name '*.o' ! -path 'build/main.o' -print)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/LivingWorldContentTest.cpp $PROJECT_OBJECTS_LIVING -o "$LIVING_WORLD_TEST_BIN"
"$LIVING_WORLD_TEST_BIN" >/dev/null || fail "contenu vivant/langues/PNJ invalide"
rm -f "$LIVING_WORLD_TEST_BIN"
pass "traces multilingues d'exploration et profils PNJ vivants testés"

BIOME_INTERACTION_TEST_BIN="$(mktemp /tmp/dinotofu_biome_interaction_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/BiomeNonCombatInteractionSystemTest.cpp src/adventure/content/BiomeNonCombatInteractionSystem.cpp -o "$BIOME_INTERACTION_TEST_BIN"
"$BIOME_INTERACTION_TEST_BIN" >/dev/null || fail "interactions non-combat de biome invalides"
rm -f "$BIOME_INTERACTION_TEST_BIN"
grep -q 'BiomeNonCombatInteractionSystem::buildCurrentInteraction' src/interface/menu/quest/QuestExplorationMenu.cpp || fail "interactions non-combat non reliées à l'exploration"
grep -q 'interactions_non_combat_biome' src/interface/menu/quest/QuestExplorationMenu.cpp || fail "anti-farm des interactions de biome absent"
pass "interactions non-combat contextuelles de biome testées"

NPC_RELATION_TEST_BIN="$(mktemp /tmp/dinotofu_npc_relationship_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/NpcRelationshipSystemTest.cpp src/world/npc/NpcRelationshipSystem.cpp -o "$NPC_RELATION_TEST_BIN"
"$NPC_RELATION_TEST_BIN" >/dev/null || fail "relations nommées entre PNJ invalides"
rm -f "$NPC_RELATION_TEST_BIN"
grep -q 'NpcRelationshipSystem::relayModifier' src/world/npc/NpcInformationPropagationSystem.cpp || fail "relations PNJ non reliées à la propagation"
pass "relations PNJ influençant la circulation des informations testées"

NPC_PROPAGATION_TEST_BIN="$(mktemp /tmp/dinotofu_npc_propagation_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/NpcInformationPropagationSystemTest.cpp $PROJECT_OBJECTS_LIVING -o "$NPC_PROPAGATION_TEST_BIN"
"$NPC_PROPAGATION_TEST_BIN" >/dev/null || fail "propagation locale des informations PNJ invalide"
rm -f "$NPC_PROPAGATION_TEST_BIN"
grep -q 'rumeur_locale' src/world/npc/NpcInformationPropagationSystem.cpp || fail "chaîne de source locale absente"
grep -q 'spontaneousIntroLines' src/interface/menu/quest/QuestMenu.cpp || fail "prises de parole spontanées PNJ non reliées"
pass "circulation locale sourcée des informations PNJ testée"

NPC_INTERCITY_TEST_BIN="$(mktemp /tmp/dinotofu_npc_intercity_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/NpcIntercityInformationSystemTest.cpp $PROJECT_OBJECTS_LIVING -o "$NPC_INTERCITY_TEST_BIN"
"$NPC_INTERCITY_TEST_BIN" >/dev/null || fail "circulation inter-ville des informations PNJ invalide"
rm -f "$NPC_INTERCITY_TEST_BIN"
grep -q 'intercityTravelDelayDays' src/world/npc/NpcInformationPropagationSystem.cpp || fail "délai inter-ville des rumeurs absent"
grep -q 'messager_de_garde' src/world/npc/NpcInformationPropagationSystem.cpp || fail "canaux physiques inter-ville absents"
pass "circulation inter-ville temporisée et sourcée des informations PNJ testée"

SAVE_TEST_BIN="$(mktemp /tmp/dinotofu_save_roundtrip_test.XXXXXX)"
PROJECT_OBJECTS="$(find build -name '*.o' ! -path 'build/main.o' -print)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/SaveRoundTripTest.cpp $PROJECT_OBJECTS -o "$SAVE_TEST_BIN"
SAVE_TEST_DIR="$(mktemp -d /tmp/dinotofu_save_roundtrip_run.XXXXXX)"
( cd "$SAVE_TEST_DIR" && "$SAVE_TEST_BIN" >/dev/null ) || fail "round-trip ou migration de sauvegarde langue invalide"
rm -rf "$SAVE_TEST_DIR" "$SAVE_TEST_BIN"
pass "round-trip sauvegarde V3.50 et migration sans languageState testés"

CHECKPOINT_TEST_BIN="$(mktemp /tmp/dinotofu_important_checkpoint_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/ImportantSaveCheckpointTest.cpp $PROJECT_OBJECTS -o "$CHECKPOINT_TEST_BIN"
CHECKPOINT_TEST_DIR="$(mktemp -d /tmp/dinotofu_important_checkpoint_run.XXXXXX)"
( cd "$CHECKPOINT_TEST_DIR" && "$CHECKPOINT_TEST_BIN" >/dev/null ) || fail "point de sauvegarde important V3.50.12 invalide"
rm -rf "$CHECKPOINT_TEST_DIR" "$CHECKPOINT_TEST_BIN"
grep -q 'return "3.50.12";' src/core/VersionInfo.cpp || fail "jalon de sauvegarde important V3.50.12 absent"
grep -q 'POINT DE SAUVEGARDE IMPORTANT' src/save/menu/CharacterMenu.cpp || fail "rituel de transition obligatoire absent"
grep -q 'createImportantUpdateBackup' src/save/menu/CharacterMenu.cpp || fail "backup pré-mise-à-jour non branché au chargement"
pass "point de sauvegarde important, backup non écrasant et rituel de transition testés"

LEGACY_MIGRATION_TEST_BIN="$(mktemp /tmp/dinotofu_legacy_migration_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/LegacySaveMigrationTest.cpp $PROJECT_OBJECTS -o "$LEGACY_MIGRATION_TEST_BIN"
LEGACY_MIGRATION_TEST_DIR="$(mktemp -d /tmp/dinotofu_legacy_migration_run.XXXXXX)"
( cd "$LEGACY_MIGRATION_TEST_DIR" && "$LEGACY_MIGRATION_TEST_BIN" >/dev/null ) || fail "migration forcée des anciennes sauvegardes invalide"
rm -rf "$LEGACY_MIGRATION_TEST_DIR" "$LEGACY_MIGRATION_TEST_BIN"
grep -q 'if (!saved.known)' src/core/VersionInfo.cpp || fail "anciennes sauvegardes non versionnées non forcées vers le checkpoint"
grep -q 'createdForVersion", summary.gameVersion' src/save/SaveManager.cpp || fail "fallback gameVersion des anciennes sauvegardes absent"
pass "anciennes sauvegardes versionnées ou non forcées vers la migration V3.50.12"

# Updater compatibility: old configs using the historical placeholder must be repaired automatically.
grep -q 'TON_COMPTE/TON_REPO' tools/linux/DinotofuLauncher.sh || fail "compatibilité placeholder repo absente du launcher Linux"
grep -q 'SIMON-Louis-2326101aa/ProjetDinotofu' tools/linux/DinotofuLauncher.sh || fail "repo GitHub par défaut absent du launcher Linux"
grep -q 'TON_COMPTE/TON_REPO' tools/windows/DinotofuLauncher.ps1 || fail "compatibilité placeholder repo absente du launcher Windows"
grep -q 'SIMON-Louis-2326101aa/ProjetDinotofu' tools/windows/DinotofuLauncher.ps1 || fail "repo GitHub par défaut absent du launcher Windows"
grep -q 'REPO_NAME="$(detect_repo_name)"' scripts/package_linux_release.sh || fail "repo release Linux non résolu automatiquement"
grep -q 'REPO_NAME="$(detect_repo_name)"' scripts/package_windows_release.sh || fail "repo release Windows non résolu automatiquement"
grep -q 'RELEASE_HAS_REQUIRED_ASSETS' .github/workflows/release-dinotofu.yml || fail "workflow GitHub ne répare plus les releases incomplètes"
grep -q 'cp -r assets "${STAGING_DIR}/"' scripts/package_linux_release.sh || fail "pack Linux ne conserve plus le layout assets historique"
grep -q 'cp -r assets "${STAGING_DIR}/"' scripts/package_windows_release.sh || fail "pack Windows ne conserve plus le layout assets historique"
pass "mise à jour des anciennes installations et packaging historique protégés"

[[ -f include/save/SaveSchemaVersion.hpp ]] || fail "version de schéma de sauvegarde centralisée absente"
grep -q -- '--save-schema' scripts/bump_version.py || fail "bump_version.py ne sait pas proposer le changement de saveVersion"
grep -q -- '--checkpoint' scripts/bump_version.py || fail "bump_version.py ne sait pas proposer un nouveau checkpoint obligatoire"
grep -q 'Changer aussi le schéma de sauvegarde' scripts/bump_version.py || fail "question interactive saveVersion absente"
grep -q 'NOUVEAU checkpoint obligatoire' scripts/bump_version.py || fail "question interactive checkpoint absent"
grep -q 'Installer-Dinotofu-Windows-v${VERSION}.7z' .github/workflows/release-dinotofu.yml || fail "asset installateur Windows absent du workflow"
grep -q 'Installer-Dinotofu-Linux-v${VERSION}.7z' .github/workflows/release-dinotofu.yml || fail "asset installateur Linux absent du workflow"
grep -q -- '--target "${GITHUB_SHA}"' .github/workflows/release-dinotofu.yml || fail "création de release après build non ciblée sur le commit courant"
[[ -x scripts/trigger_release.sh ]] || fail "helper de déclenchement manuel GitHub absent/non exécutable"
grep -q 'exactement 2 entrees' scripts/package_linux_release.sh || fail "layout propre du pack installateur Linux non protégé"
grep -q 'exactement 2 entrees' scripts/package_windows_release.sh || fail "layout propre du pack installateur Windows non protégé"
[[ -x scripts/stage_release_documentation.sh ]] || fail "helper de documentation des packs installateur absent/non exécutable"
grep -q 'INSTALLATION.txt' scripts/stage_release_documentation.sh || fail "documentation des packs installateur non centralisée"
pass "versioning sauvegarde, release GitHub manuelle/auto et packs installateur propres protégés"

grep -q 'persistentId' include/item/Item.hpp || fail "identité persistante Item absente"
grep -q 'Mémoire de cet exemplaire' src/interface/menu/EquipmentMenu.cpp || fail "inspection mémoire équipement absente"
grep -q 'Surnom émergent' src/interface/menu/EquipmentMenu.cpp || fail "renommée émergente d'équipement absente"
grep -q 'item_memory_enemy_signature' src/combat/turn/wave/MonsterWaveCombatTurn.cpp || fail "mémoire d'impact sur exemplaire absente"
grep -q 'item_memory_transferred_sale' src/economy/shop/ShopTransactionSystem.cpp || fail "mémoire de vente d'un exemplaire absente"
grep -q 'item_memory_recovered_after_sale' src/economy/shop/ShopTransactionSystem.cpp || fail "mémoire de rachat du même exemplaire absente"
pass "identité, mémoire et renommée d'équipement présentes"

grep -q 'Technique combinée' src/combat/modes/pve/MonsterPveMode.cpp || fail "technique combinée alliée absente"
grep -q 'groupCombinedTechniqueOneTurn' src/combat/modes/pve/MonsterPveMode.cpp || fail "ordre de combo allié absent"
[[ -f include/combat/ally/DuoMasterySystem.hpp && -f src/combat/ally/DuoMasterySystem.cpp ]] || fail "maîtrise des duos non modularisée"
grep -q 'DuoMasterySystem::experience' src/combat/modes/pve/MonsterPveMode.cpp || fail "expérience persistante des duos non reliée au combat"
grep -q 'Relais vital' src/combat/ally/DuoMasterySystem.cpp || fail "combo soutien+soutien absent"
grep -q 'Mur en mouvement' src/combat/ally/DuoMasterySystem.cpp || fail "combo tank+tank absent"
grep -q 'coordination rompue' src/combat/modes/pve/MonsterPveMode.cpp || fail "échec logique des combos absent"
DUO_TEST_BIN="$(mktemp /tmp/dinotofu_duo_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/DuoMasterySystemTest.cpp $PROJECT_OBJECTS -o "$DUO_TEST_BIN"
"$DUO_TEST_BIN" >/dev/null || fail "maîtrise/variantes des duos invalides"
rm -f "$DUO_TEST_BIN"
pass "techniques combinées et maîtrise de duo modularisées/testées"

[[ -f include/combat/EnemyCombatQueue.hpp && -f src/combat/EnemyCombatQueue.cpp ]] || fail "file ennemie absente"
grep -q 'getSurrenderedEnemyCount' include/combat/EnemyCombatQueue.hpp || fail "état de reddition absent de la file ennemie"
grep -q 'REDDITION ENNEMIE' src/combat/turn/wave/MonsterWaveCombatTurn.cpp || fail "reddition réelle absente du combat"
grep -q 'chocs_de_groupe_ennemis' src/combat/turn/wave/MonsterWaveCombatTurn.cpp || fail "réaction à la chute du meneur absente"
grep -q 'calculateSurrenderedEnemiesReward' src/combat/reward/CombatRewardSystem.cpp || fail "récompense de reddition non séparée"
GROUP_TEST_BIN="$(mktemp /tmp/dinotofu_enemy_group_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/EnemyGroupBehaviorTest.cpp $PROJECT_OBJECTS -o "$GROUP_TEST_BIN"
"$GROUP_TEST_BIN" >/dev/null || fail "reddition/file ennemie/profils de groupe invalides"
rm -f "$GROUP_TEST_BIN"
pass "reddition et réactions de groupe ennemies présentes/testées"

MONSTER_PREPARED_TEST_BIN="$(mktemp /tmp/dinotofu_monster_prepared_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/MonsterPreparedActionSystemTest.cpp $PROJECT_OBJECTS -o "$MONSTER_PREPARED_TEST_BIN"
"$MONSTER_PREPARED_TEST_BIN" >/dev/null || fail "compétences préparées/interrompables ennemies invalides"
rm -f "$MONSTER_PREPARED_TEST_BIN"
grep -q 'COMPÉTENCE INTERROMPUE' src/combat/turn/wave/MonsterWaveCombatTurn.cpp || fail "feedback d'interruption ennemi absent"
grep -q 'startPreparedSignature' src/combat/turn/wave/MonsterWaveCombatTurn.cpp || fail "préparation ennemie non reliée au tour"
grep -q 'COUVERTURE DE PRÉPARATION' src/combat/turn/wave/MonsterWaveCombatTurn.cpp || fail "protection de compétence préparée absente"
pass "compétences ennemies préparées, variantes, interruption et protection de groupe testées"

MONSTER_CONTENT_TEST_BIN="$(mktemp /tmp/dinotofu_monster_content_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/MonsterContentExpansionTest.cpp $PROJECT_OBJECTS -o "$MONSTER_CONTENT_TEST_BIN"
"$MONSTER_CONTENT_TEST_BIN" >/dev/null || fail "nouveaux monstres de biomes absents du catalogue"
rm -f "$MONSTER_CONTENT_TEST_BIN"
pass "nouvelles familles de monstres de biomes présentes"

MONSTER_FLAVOR_LIFECYCLE_TEST_BIN="$(mktemp /tmp/dinotofu_monster_flavor_lifecycle_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/MonsterFlavorLifecycleTest.cpp $PROJECT_OBJECTS -o "$MONSTER_FLAVOR_LIFECYCLE_TEST_BIN"
"$MONSTER_FLAVOR_LIFECYCLE_TEST_BIN" >/dev/null || fail "descriptions de mort/fuite/reddition par créature invalides"
rm -f "$MONSTER_FLAVOR_LIFECYCLE_TEST_BIN"
grep -q 'buildSurrenderLine' src/combat/turn/wave/MonsterWaveCombatTurn.cpp || fail "description de reddition non reliée"
grep -q 'buildDeathLine' src/combat/EnemyCombatQueue.cpp || fail "description de mort non reliée"
pass "mort, fuite et reddition décrites selon la créature"

grep -q 'SERMENT DÉJÀ ROMPU' src/interface/menu/shop/ChurchServiceMenu.cpp || fail "protection de rupture de serment absente"
grep -q 'isChurchOathContractId' src/entity/player/PlayerSkills.cpp || fail "contrats d'église non séparés du loadout"
pass "serments gérés comme contrats hors loadout"

[[ -f include/world/LocalReputationSystem.hpp && -f src/world/LocalReputationSystem.cpp ]] || fail "réputation locale centralisée absente"
grep -q 'canonicalCategoryIsLocalScoped' src/entity/Player.cpp || fail "journal localisé non protégé"
grep -q 'surchargeForScore' src/world/LocalReputationSystem.cpp || fail "conséquences de réputation négative absentes"
grep -q 'vente importante refusée' src/interface/menu/shop/ShopMenu.cpp || fail "réaction commerciale négative absente"
[[ -f include/world/LocalReputationRepairSystem.hpp && -f src/world/LocalReputationRepairSystem.cpp ]] || fail "réhabilitation de réputation locale absente"
grep -q 'LocalReputationRepairMenu::open' src/interface/menu/quest/QuestLocationNpcMenu.cpp || fail "bureau de médiation locale non relié aux lieux"
REPUTATION_REPAIR_TEST_BIN="$(mktemp /tmp/dinotofu_reputation_repair_test.XXXXXX)"
g++ -std=c++17 -Wall -Wextra -Iinclude tests/LocalReputationRepairSystemTest.cpp $PROJECT_OBJECTS -o "$REPUTATION_REPAIR_TEST_BIN"
"$REPUTATION_REPAIR_TEST_BIN" >/dev/null || fail "réhabilitation de réputation locale invalide"
rm -f "$REPUTATION_REPAIR_TEST_BIN"
pass "journal localisé, réputation positive/négative et réhabilitation présents/testés"

grep -q 'FIN TEMPORAIRE DU DÉVELOPPEMENT HISTOIRE' src/core/GameStory.cpp || fail "limite histoire absente"
grep -q 'return false;' src/story/StoryCampaign.cpp || fail "verrou développement histoire absent"
pass "limite histoire après introduction chapitre 3 présente"

grep -q 'Mémoire du monde / Rivaux' src/interface/menu/progression/StatisticsMenu.cpp || fail "inspection mémoire monde absente"
pass "inspection mémoire/rivaux disponible"

echo "Tous les tests Dinotofu sont passés."
